services:
  flask-app:
    build:
      context: ./python
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=dbname
      - DB_USER=youruser
      - DB_PASSWORD=newpassword
      - DB_HOST=postgres
    depends_on:
      - postgres
    command: bash -c 'sleep 10 && python app.py'

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app      
    # mount the TLS certificates from the host machine to the container
    # change <your-domain> to your DNS
    volumes:
      - /etc/letsencrypt/live/k8scourse.duckdns.org/fullchain.pem:/etc/letsencrypt/live/k8scourse.duckdns.org/fullchain.pem
      - /etc/letsencrypt/live/k8scourse.duckdns.org/privkey.pem:/etc/letsencrypt/live/k8scourse.duckdns.org/privkey.pem
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: newpassword
