imagePullSecrets:
  - name: your-regcred

ingress:
  enabled: true
  className: traefik
  annotations: 
     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
     cert-manager.io/cluster-issuer: # use the value from `kubectl get clusterissuer`
  hosts:
    - host: k8scourse.duckdns.org
      paths:
        - path: /
          pathType: Prefix
          service:
            name: nginx
            port: 80
        - path: # add your prefix here for the backend
          pathType: Prefix
          service:
            name: # your backend service name
            port: # what port do you want to forward traffic on your backend?
  tls: 
   - secretName: nginx-tls-secret
     hosts:
       - k8scourse.duckdns.org   # what is the domain you should use here?
