# k8s/cert-manager/issuer.yaml

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # replace with your own email
    email: jacques.gemors.pos@gmail.com
    
    # secret resource that will be used to store the account's private key
    privateKeySecretRef:
      name: letsencrypt-staging    
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
